import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Business, BusinessCategory } from '../business/entities/business.entity';

@Injectable()
export class SeedService {
  constructor(
    @InjectRepository(Business)
    private businessRepository: Repository<Business>,
  ) {}

  async seed() {
    const count = await this.businessRepository.count();
    if (count > 0) {
      console.log('Database already seeded');
      return;
    }

    const sampleBusinesses = [
      {
        name: 'Elite Car Rentals',
        description: 'Premium car rental service offering luxury vehicles for business and leisure. Wide selection of sedans, SUVs, and exotic cars available for daily, weekly, or monthly rentals.',
        category: BusinessCategory.VEHICLES,
        website: 'https://elitecarrentals.example.com',
        phone: '+1-555-0101',
        email: 'info@elitecarrentals.example.com',
        address: '123 Main Street',
        city: 'New York',
        state: 'NY',
        country: 'United States',
        zipCode: '10001',
        latitude: 40.7128,
        longitude: -74.0060,
        rentalItems: ['Luxury Sedans', 'SUVs', 'Sports Cars', 'Vans'],
        amenities: ['GPS Navigation', 'Insurance', '24/7 Support', 'Free Delivery'],
        rating: 4.8,
        reviewCount: 245,
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Prime Property Rentals',
        description: 'Vacation and short-term property rentals in prime locations. From beachfront villas to mountain cabins, find your perfect getaway.',
        category: BusinessCategory.PROPERTIES,
        website: 'https://primepropertyrentals.example.com',
        phone: '+1-555-0202',
        email: 'bookings@primepropertyrentals.example.com',
        address: '456 Ocean Drive',
        city: 'Miami',
        state: 'FL',
        country: 'United States',
        zipCode: '33139',
        latitude: 25.7617,
        longitude: -80.1918,
        rentalItems: ['Vacation Homes', 'Apartments', 'Villas', 'Cabins'],
        amenities: ['Wifi', 'Pool', 'Parking', 'Kitchen', 'Air Conditioning'],
        rating: 4.9,
        reviewCount: 189,
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Construction Equipment Co',
        description: 'Industrial equipment rental for construction and development projects. Heavy machinery, power tools, and scaffolding available.',
        category: BusinessCategory.EQUIPMENT,
        website: 'https://constructionequipco.example.com',
        phone: '+1-555-0303',
        email: 'rentals@constructionequipco.example.com',
        address: '789 Industrial Blvd',
        city: 'Houston',
        state: 'TX',
        country: 'United States',
        zipCode: '77002',
        latitude: 29.7604,
        longitude: -95.3698,
        rentalItems: ['Excavators', 'Forklifts', 'Cranes', 'Power Tools', 'Scaffolding'],
        amenities: ['Delivery', 'Operator Training', 'Maintenance', '24/7 Emergency Support'],
        rating: 4.7,
        reviewCount: 156,
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Party Perfect Events',
        description: 'Complete event rental solutions for weddings, corporate events, and parties. Tents, tables, chairs, lighting, and audiovisual equipment.',
        category: BusinessCategory.EVENTS,
        website: 'https://partyperfectevents.example.com',
        phone: '+1-555-0404',
        email: 'events@partyperfectevents.example.com',
        address: '321 Event Plaza',
        city: 'Los Angeles',
        state: 'CA',
        country: 'United States',
        zipCode: '90001',
        latitude: 34.0522,
        longitude: -118.2437,
        rentalItems: ['Tents', 'Tables & Chairs', 'Lighting', 'Audio Equipment', 'Decorations'],
        amenities: ['Setup Service', 'Design Consultation', 'Delivery', 'Breakdown Service'],
        rating: 4.9,
        reviewCount: 312,
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Adventure Sports Rentals',
        description: 'Outdoor recreation equipment for all your adventures. Bikes, kayaks, camping gear, and winter sports equipment.',
        category: BusinessCategory.RECREATION,
        website: 'https://adventuresportsrentals.example.com',
        phone: '+1-555-0505',
        email: 'info@adventuresportsrentals.example.com',
        address: '654 Mountain Road',
        city: 'Denver',
        state: 'CO',
        country: 'United States',
        zipCode: '80202',
        latitude: 39.7392,
        longitude: -104.9903,
        rentalItems: ['Mountain Bikes', 'Kayaks', 'Camping Gear', 'Ski Equipment', 'Snowboards'],
        amenities: ['Expert Advice', 'Guided Tours', 'Safety Equipment Included', 'Local Maps'],
        rating: 4.8,
        reviewCount: 278,
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Tech Gadget Rentals',
        description: 'Latest electronics and technology for rent. Cameras, laptops, gaming consoles, VR headsets, and more for short or long-term use.',
        category: BusinessCategory.ELECTRONICS,
        website: 'https://techgadgetrentals.example.com',
        phone: '+1-555-0606',
        email: 'support@techgadgetrentals.example.com',
        address: '987 Tech Avenue',
        city: 'San Francisco',
        state: 'CA',
        country: 'United States',
        zipCode: '94102',
        latitude: 37.7749,
        longitude: -122.4194,
        rentalItems: ['Laptops', 'Cameras', 'Drones', 'Gaming Consoles', 'VR Headsets', 'Projectors'],
        amenities: ['Insurance Options', 'Technical Support', 'Quick Delivery', 'Flexible Terms'],
        rating: 4.6,
        reviewCount: 198,
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Urban Furniture Rentals',
        description: 'Stylish furniture rentals for homes, offices, and events. Modern and classic pieces available for any duration.',
        category: BusinessCategory.FURNITURE,
        website: 'https://urbanfurniturerentals.example.com',
        phone: '+1-555-0707',
        email: 'rentals@urbanfurniturerentals.example.com',
        address: '147 Design Street',
        city: 'Chicago',
        state: 'IL',
        country: 'United States',
        zipCode: '60601',
        latitude: 41.8781,
        longitude: -87.6298,
        rentalItems: ['Living Room Sets', 'Bedroom Furniture', 'Office Furniture', 'Dining Sets'],
        amenities: ['White Glove Delivery', 'Assembly Service', 'Flexible Packages', 'Designer Consultation'],
        rating: 4.7,
        reviewCount: 167,
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Pro Tool Rentals',
        description: 'Professional-grade tools for contractors and DIY enthusiasts. Power tools, hand tools, and specialty equipment.',
        category: BusinessCategory.TOOLS,
        website: 'https://protoolrentals.example.com',
        phone: '+1-555-0808',
        email: 'info@protoolrentals.example.com',
        address: '258 Workshop Lane',
        city: 'Phoenix',
        state: 'AZ',
        country: 'United States',
        zipCode: '85001',
        latitude: 33.4484,
        longitude: -112.0740,
        rentalItems: ['Power Drills', 'Saws', 'Sanders', 'Nail Guns', 'Welding Equipment'],
        amenities: ['Safety Training', 'Tool Delivery', 'Replacement Guarantee', 'Bulk Discounts'],
        rating: 4.8,
        reviewCount: 223,
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'London Luxury Motors',
        description: 'Prestige car hire in central London. Chauffeur-driven or self-drive options for weddings, corporate events, and special occasions.',
        category: BusinessCategory.VEHICLES,
        website: 'https://londonluxurymotors.example.com',
        phone: '+44-20-5555-0101',
        email: 'bookings@londonluxurymotors.example.com',
        address: '42 Park Lane',
        city: 'London',
        state: 'England',
        country: 'United Kingdom',
        zipCode: 'W1K 7AA',
        latitude: 51.5074,
        longitude: -0.1278,
        rentalItems: ['Luxury Cars', 'Wedding Cars', 'Chauffeur Service', 'Executive Vehicles'],
        amenities: ['Professional Chauffeurs', 'Airport Transfers', 'Corporate Accounts', 'Red Carpet Service'],
        rating: 4.9,
        reviewCount: 342,
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Sydney Beachside Properties',
        description: 'Premium beachfront accommodation rentals in Sydney. Stunning ocean views and modern amenities for unforgettable stays.',
        category: BusinessCategory.PROPERTIES,
        website: 'https://sydneybeachsideproperties.example.com',
        phone: '+61-2-5555-0202',
        email: 'stay@sydneybeachsideproperties.example.com',
        address: '88 Bondi Beach Road',
        city: 'Sydney',
        state: 'New South Wales',
        country: 'Australia',
        zipCode: '2026',
        latitude: -33.8688,
        longitude: 151.2093,
        rentalItems: ['Beach Houses', 'Apartments', 'Penthouses', 'Holiday Homes'],
        amenities: ['Ocean Views', 'Wifi', 'Pool', 'Parking', 'Concierge Service'],
        rating: 4.8,
        reviewCount: 267,
        isActive: true,
        isFeatured: true,
      },
    ];

    for (const businessData of sampleBusinesses) {
      const business = this.businessRepository.create(businessData);
      await this.businessRepository.save(business);
    }

    console.log(`Seeded ${sampleBusinesses.length} businesses successfully`);
  }
}
